version: '3.8'

services:
  api-go:
    build: ./zitch-backend
    expose:
      - "4000"
    networks:
      - zitch-network

  classifier:
    build: ./classifier
    expose:
      - "50051"
    networks:
      - zitch-network

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-go
      - classifier
    networks:
      - zitch-network

networks:
  zitch-network:
