# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x18\n\x05Image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"/\n\nPrediction\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x05\x32\x41\n\tInference\x12\x34\n\x07Predict\x12\x10.inference.Image\x1a\x15.inference.Prediction\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=30
  _globals['_IMAGE']._serialized_end=54
  _globals['_PREDICTION']._serialized_start=56
  _globals['_PREDICTION']._serialized_end=103
  _globals['_INFERENCE']._serialized_start=105
  _globals['_INFERENCE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
